In [32]:
# train Char-GAN

# create font image dataset
# %cd /notebooks/CoordConv-pytorch/font2img
# !python font2img.py \
#     /notebooks/post-generator/asset/fonts_en/Alegreya \
#     /notebooks/CoordConv-pytorch/font2img/src_chars_txt/alphabets_hankaku_caps.txt \
#     /notebooks/CoordConv-pytorch/data//fontimg \
#     --by-char

# train Char-GAN
# %cd /notebooks/CoordConv-pytorch/gan-char
# !python train.py --sample_interval 30

[1, 2]

In [4]:
%cd /notebooks/CoordConv-pytorch/gan-textbox
# !rm -R data/regressor
# !python -m experiments.regressor.train_shape --img_size=64 --n_epochs=100 --n_strokes=4 --sample_interval=10 --n_samples=10
!python train_toy_pasteline.py --batch_size=1

/notebooks/CoordConv-pytorch/gan_textbox
Namespace(b1=0.5, b2=0.999, batch_size=1, channels=1, clip_value=0.01, data_path='data/layout', img_size=28, latent_dim=10, lr=0.0002, model_path='saved_models/95000.pt', n_cpu=8, n_critic=50, n_epochs=200, sample_interval=400)
tensor([[ 0.6609,  0.3852, 12.6609, 13.3852]], grad_fn=<SqueezeBackward1>)
tensor([[12.6609,  0.3852, 20.6609, 13.3852]], grad_fn=<SqueezeBackward1>)
tensor([[20.6609,  0.3852, 23.6609, 13.3852]], grad_fn=<SqueezeBackward1>)
tensor([[23.6609,  0.3852, 31.6609, 13.3852]], grad_fn=<SqueezeBackward1>)
tensor([[31.6609,  0.3852, 31.6609,  0.3852]], grad_fn=<SqueezeBackward1>)
tensor([[31.6609,  0.3852, 31.6609,  0.3852]], grad_fn=<SqueezeBackward1>)
tensor([[31.6609,  0.3852, 31.6609,  0.3852]], grad_fn=<SqueezeBackward1>)
tensor([[31.6609,  0.3852, 31.6609,  0.3852]], grad_fn=<SqueezeBackward1>)
tensor([[31.6609,  0.3852, 31.6609,  0.3852]], grad_fn=<SqueezeBackward1>)
tensor([[31.6609,  0.3852, 31.6609,  0.3852]], grad_fn=<

tensor([[40.6599,  0.3978, 40.6599,  0.3978]], grad_fn=<SqueezeBackward1>)
tensor([[40.6599,  0.3978, 40.6599,  0.3978]], grad_fn=<SqueezeBackward1>)
tensor([[40.6599,  0.3978, 40.6599,  0.3978]], grad_fn=<SqueezeBackward1>)
tensor([[ 0.6583,  0.4185,  8.6583, 16.4185]], grad_fn=<SqueezeBackward1>)
tensor([[ 8.6583,  0.4185, 16.6583, 13.4185]], grad_fn=<SqueezeBackward1>)
tensor([[16.6583,  0.4185, 23.6583, 13.4185]], grad_fn=<SqueezeBackward1>)
tensor([[23.6583,  0.4185, 26.6583, 13.4185]], grad_fn=<SqueezeBackward1>)
tensor([[26.6583,  0.4185, 31.6583, 13.4185]], grad_fn=<SqueezeBackward1>)
tensor([[31.6583,  0.4185, 34.6583, 13.4185]], grad_fn=<SqueezeBackward1>)
tensor([[34.6583,  0.4185, 41.6583, 13.4185]], grad_fn=<SqueezeBackward1>)
tensor([[41.6583,  0.4185, 48.6583, 13.4185]], grad_fn=<SqueezeBackward1>)
tensor([[48.6583,  0.4185, 48.6583,  0.4185]], grad_fn=<SqueezeBackward1>)
tensor([[48.6583,  0.4185, 48.6583,  0.4185]], grad_fn=<SqueezeBackward1>)
tensor([[ 0.6605,  0.3588

tensor([[ 0.6567,  0.4190,  8.6567, 13.4190]], grad_fn=<SqueezeBackward1>)
tensor([[ 8.6567,  0.4190, 16.6567, 13.4190]], grad_fn=<SqueezeBackward1>)
tensor([[16.6567,  0.4190, 21.6567, 13.4190]], grad_fn=<SqueezeBackward1>)
tensor([[21.6567,  0.4190, 29.6567, 13.4190]], grad_fn=<SqueezeBackward1>)
tensor([[29.6567,  0.4190, 34.6567, 13.4190]], grad_fn=<SqueezeBackward1>)
tensor([[34.6567,  0.4190, 42.6567, 13.4190]], grad_fn=<SqueezeBackward1>)
tensor([[42.6567,  0.4190, 45.6567, 13.4190]], grad_fn=<SqueezeBackward1>)
tensor([[45.6567,  0.4190, 45.6567,  0.4190]], grad_fn=<SqueezeBackward1>)
tensor([[45.6567,  0.4190, 45.6567,  0.4190]], grad_fn=<SqueezeBackward1>)
tensor([[45.6567,  0.4190, 45.6567,  0.4190]], grad_fn=<SqueezeBackward1>)
tensor([[ 0.6588,  0.3866,  8.6588, 13.3866]], grad_fn=<SqueezeBackward1>)
tensor([[ 8.6588,  0.3866, 19.6588, 13.3866]], grad_fn=<SqueezeBackward1>)
tensor([[19.6588,  0.3866, 27.6588, 13.3866]], grad_fn=<SqueezeBackward1>)
tensor([[27.6588,  0.3866

tensor([[ 0.6600,  0.3761,  7.6600, 13.3761]], grad_fn=<SqueezeBackward1>)
tensor([[ 7.6600,  0.3761, 15.6600, 13.3761]], grad_fn=<SqueezeBackward1>)
tensor([[15.6600,  0.3761, 20.6600, 13.3761]], grad_fn=<SqueezeBackward1>)
tensor([[20.6600,  0.3761, 28.6600, 13.3761]], grad_fn=<SqueezeBackward1>)
tensor([[28.6600,  0.3761, 28.6600,  0.3761]], grad_fn=<SqueezeBackward1>)
tensor([[28.6600,  0.3761, 28.6600,  0.3761]], grad_fn=<SqueezeBackward1>)
tensor([[28.6600,  0.3761, 28.6600,  0.3761]], grad_fn=<SqueezeBackward1>)
tensor([[28.6600,  0.3761, 28.6600,  0.3761]], grad_fn=<SqueezeBackward1>)
tensor([[28.6600,  0.3761, 28.6600,  0.3761]], grad_fn=<SqueezeBackward1>)
tensor([[28.6600,  0.3761, 28.6600,  0.3761]], grad_fn=<SqueezeBackward1>)
tensor([[ 0.6604,  0.3711,  8.6604, 13.3711]], grad_fn=<SqueezeBackward1>)
tensor([[ 8.6604,  0.3711, 16.6604, 13.3711]], grad_fn=<SqueezeBackward1>)
tensor([[16.6604,  0.3711, 27.6604, 13.3711]], grad_fn=<SqueezeBackward1>)
tensor([[27.6604,  0.3711

tensor([[ 0.6590,  0.4101,  8.6590, 16.4101]], grad_fn=<SqueezeBackward1>)
tensor([[ 8.6590,  0.4101, 13.6590, 13.4101]], grad_fn=<SqueezeBackward1>)
tensor([[13.6590,  0.4101, 21.6590, 13.4101]], grad_fn=<SqueezeBackward1>)
tensor([[21.6590,  0.4101, 26.6590, 13.4101]], grad_fn=<SqueezeBackward1>)
tensor([[26.6590,  0.4101, 33.6590, 13.4101]], grad_fn=<SqueezeBackward1>)
tensor([[33.6590,  0.4101, 40.6590, 13.4101]], grad_fn=<SqueezeBackward1>)
tensor([[40.6590,  0.4101, 45.6590, 13.4101]], grad_fn=<SqueezeBackward1>)
tensor([[45.6590,  0.4101, 45.6590,  0.4101]], grad_fn=<SqueezeBackward1>)
tensor([[45.6590,  0.4101, 45.6590,  0.4101]], grad_fn=<SqueezeBackward1>)
tensor([[45.6590,  0.4101, 45.6590,  0.4101]], grad_fn=<SqueezeBackward1>)
tensor([[ 0.6571,  0.4278,  5.6571, 13.4278]], grad_fn=<SqueezeBackward1>)
tensor([[ 5.6571,  0.4278, 12.6571, 13.4278]], grad_fn=<SqueezeBackward1>)
tensor([[12.6571,  0.4278, 19.6571, 13.4278]], grad_fn=<SqueezeBackward1>)
tensor([[19.6571,  0.4278

In [11]:
%cd /notebooks/CoordConv-pytorch/experiments/gan/munit
!rm -R data
!rm -R images
# !rm -R saved_models
!python train_layout_by_params.py --n_epochs=100000 --latent_dim=4 --channels=1 --img_size=64 --n_critic=1 --sample_interval=100

/notebooks/CoordConv-pytorch/experiments/gan/munit
Namespace(b1=0.5, b2=0.999, batch_size=64, channels=1, clip_value=0.01, data_path='data/layout', img_size=64, latent_dim=4, lr=0.0002, model_path='saved_models/95000.pt', n_cpu=8, n_critic=1, n_epochs=100000, sample_interval=100)
[Epoch 0/100000] [Batch 0/2] [D loss: 8.145257] [G loss: 7.907234]
^C
Traceback (most recent call last):
  File "train_layout_by_params.py", line 351, in <module>
    train_wgan()
  File "train_layout_by_params.py", line 307, in train_wgan
    discriminator, real_imgs.data, fake_imgs.data
  File "/notebooks/CoordConv-pytorch/experiments/gan/munit/models.py", line 467, in compute_gradient_penalty
    gradient_penalty = ((gradients.norm(2, dim=1) - 1) ** 2).mean()
  File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/tensor.py", line 253, in norm
    return torch.norm(self, p, dim, keepdim, dtype=dtype)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/functional.py", line 705, in norm
    

In [12]:
18//4

4