### Docker

```bash
sudo docker run --runtime=nvidia -d -it --rm -p=8888:8888 --ipc="host" -v=/home/chi/Documents:/tf tensorflow/tensorflow:2.0.0rc0-gpu-py3-jupyter
sudo docker logs ...
sudo docker start ...
sudo docker exec -it ... /bin/bash
```


In [11]:
%cd /notebooks/CoordConv-pytorch/gan-textbox
!python train_toy_pasteline.py --img_size=64

/notebooks/CoordConv-pytorch/gan-textbox
Namespace(b1=0.5, b2=0.999, batch_size=64, channels=1, clip_value=0.01, data_path='data/layout', img_size=64, latent_dim=10, lr=0.0002, model_path='saved_models/95000.pt', n_cpu=8, n_critic=50, n_epochs=200, sample_interval=400)
[Epoch 0/200] [Batch 0/2] [D loss: 8.181931] [G loss: 0.071838]
tensor([26.2847, 34.8410], grad_fn=<SelectBackward>)
[Epoch 8/200] [Batch 0/2] [D loss: -4.030709] [G loss: 2.268535]
tensor([27.1419, 35.6031], grad_fn=<SelectBackward>)
[Epoch 16/200] [Batch 0/2] [D loss: -9.370255] [G loss: 5.008334]
tensor([28.1940, 36.4914], grad_fn=<SelectBackward>)
[Epoch 24/200] [Batch 0/2] [D loss: -9.616585] [G loss: 5.165176]
tensor([29.0184, 37.0904], grad_fn=<SelectBackward>)
[Epoch 32/200] [Batch 0/2] [D loss: -9.506098] [G loss: 4.849552]
tensor([30.2663, 37.9889], grad_fn=<SelectBackward>)
[Epoch 40/200] [Batch 0/2] [D loss: -8.929195] [G loss: 4.268219]
tensor([31.7005, 39.2088], grad_fn=<SelectBackward>)
[Epoch 48/200] [Bat

In [7]:
# create font image dataset
# %cd /notebooks/CoordConv-pytorch/font2img
# !python font2img.py \
#     /notebooks/post-generator/asset/fonts_en/Alegreya \
#     /notebooks/CoordConv-pytorch/font2img/src_chars_txt/alphabets_hankaku_caps.txt \
#     /notebooks/CoordConv-pytorch/data/fontimg
#     --by-char

# train Char-GAN
# %cd /notebooks/CoordConv-pytorch/gan-char
# !python train.py --sample_interval 30

In [13]:
%cd /notebooks/CoordConv-pytorch/gan-textbox
!python train_char_transfer_gan.py 
# !rm -R data/regressor
# !python -m experiments.regressor.train_shape --img_size=64 --n_epochs=100 --n_strokes=4 --sample_interval=10 --n_samples=10
# !python train_toy_pasteline.py --batch_size=1

/notebooks/CoordConv-pytorch/gan-textbox
Namespace(b1=0.5, b2=0.999, batch_size=1, channels=3, checkpoint_interval=-1, dataset_name='edges2shoes', decay_epoch=100, dim=64, epoch=0, img_height=128, img_width=128, lr=0.0001, n_cpu=8, n_downsample=2, n_epochs=200, n_residual=3, sample_interval=400, style_dim=8)
[Epoch 0/200] [Batch 4/234] [D loss: 6.972351] [G loss: 15.614893] ETA: 7 days, 6:19:33.33554340^C
Traceback (most recent call last):
  File "train_char_transfer_gan.py", line 353, in <module>
    optimizer_G.step()
  File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/optim/adam.py", line 101, in step
    denom = exp_avg_sq.sqrt().add_(group['eps'])
KeyboardInterrupt


In [11]:
%cd /notebooks/CoordConv-pytorch/experiments/gan/munit
!rm -R data
!rm -R images
# !rm -R saved_models
!python train_layout_by_params.py --n_epochs=100000 --latent_dim=4 --channels=1 --img_size=64 --n_critic=1 --sample_interval=100

/notebooks/CoordConv-pytorch/experiments/gan/munit
Namespace(b1=0.5, b2=0.999, batch_size=64, channels=1, clip_value=0.01, data_path='data/layout', img_size=64, latent_dim=4, lr=0.0002, model_path='saved_models/95000.pt', n_cpu=8, n_critic=1, n_epochs=100000, sample_interval=100)
[Epoch 0/100000] [Batch 0/2] [D loss: 8.145257] [G loss: 7.907234]
^C
Traceback (most recent call last):
  File "train_layout_by_params.py", line 351, in <module>
    train_wgan()
  File "train_layout_by_params.py", line 307, in train_wgan
    discriminator, real_imgs.data, fake_imgs.data
  File "/notebooks/CoordConv-pytorch/experiments/gan/munit/models.py", line 467, in compute_gradient_penalty
    gradient_penalty = ((gradients.norm(2, dim=1) - 1) ** 2).mean()
  File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/tensor.py", line 253, in norm
    return torch.norm(self, p, dim, keepdim, dtype=dtype)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/functional.py", line 705, in norm
    

In [12]:
18//4

4