In [ ]:
# !python experiments/regressor.py
!python experiments/regressor_rect.py

Train Epoch: 1 [8000/8000 (100%)] Loss: 2.735060
Train Epoch: 2 [8000/8000 (100%)] Loss: 1.440997
Train Epoch: 3 [8000/8000 (100%)] Loss: 0.690631
Train Epoch: 4 [8000/8000 (100%)] Loss: 1.099502
Train Epoch: 5 [8000/8000 (100%)] Loss: 1.506256
Train Epoch: 6 [8000/8000 (100%)] Loss: 0.956721
Train Epoch: 7 [8000/8000 (100%)] Loss: 0.603581
Train Epoch: 8 [8000/8000 (100%)] Loss: 1.116940
Train Epoch: 9 [8000/8000 (100%)] Loss: 1.720875


In [49]:
import numpy as np
import torch
import torch.nn as nn

# target = torch.from_numpy(np.array([[0,1,0]], dtype=int))
# y = torch.from_numpy(np.random.rand(1, 3))
# _, labels = target.max(dim=1)
# print(labels)
# f = nn.CrossEntropyLoss()
# f(y, labels)
# x = np.zeros((3,3), dtype=int)
x = np.random.rand(1, 3,3)
x[0][1][1] = 1
print(x)
x.reshape(3*3)

[[[0.53376505 0.04693572 0.38587218]
  [0.21494464 1.         0.89142348]
  [0.68461573 0.01905587 0.94046262]]]


array([0.53376505, 0.04693572, 0.38587218, 0.21494464, 1.        ,
       0.89142348, 0.68461573, 0.01905587, 0.94046262])

In [ ]:
def norm(x, width):
    return (int)(x * (width - 1) + 0.5)


def draw_rect(points, width=64):
    x0, y0, x1, y1 = points
    x0 = norm(x0, width)
    y0 = norm(y0, width)
    x1 = norm(x1, width)
    y1 = norm(y1, width)
    im = Image.new("F", (width, width))
    draw = ImageDraw.Draw(im)
    draw.rectangle([x0, y0, x1, y1], fill=1)
    im = np.array(im)  # (H, W)
    im = np.expand_dims(im, axis=-1)  # (H, W, 1)
    return im

draw