In [11]:
%cd /notebooks/CoordConv-pytorch/experiments/gan/munit/
!python train_layout.py

/notebooks/CoordConv-pytorch/experiments/gan/munit
Namespace(b1=0.5, b2=0.999, batch_size=64, channels=1, clip_value=0.01, img_size=28, latent_dim=100, lr=0.0002, n_cpu=8, n_critic=50, n_epochs=200, sample_interval=400)
/miniconda/envs/py36/lib/python3.6/site-packages/torch/nn/functional.py:1374: UserWarning: nn.functional.tanh is deprecated. Use torch.tanh instead.
  warnings.warn("nn.functional.tanh is deprecated. Use torch.tanh instead.")
0 0 1.0592478513717651
tensor([0.3125, 0.5469, 0.6250, 0.8594])
0 1 1.046953558921814
tensor([0.4062, 0.6172, 0.7188, 0.9297])
1 0 1.0350018739700317
tensor([0.1562, 0.4062, 0.4688, 0.7188])
1 1 1.02298104763031
tensor([0.0391, 0.1016, 0.3516, 0.4141])
2 0 1.010284662246704
tensor([0.5078, 0.0234, 0.8203, 0.3359])
2 1 0.9942588210105896
tensor([0.3906, 0.3047, 0.7031, 0.6172])
3 0 0.9684224724769592
tensor([0.0078, 0.1797, 0.3203, 0.4922])
3 1 0.9182800650596619
tensor([0.2188, 0.6328, 0.5312, 0.9453])
4 0 0.8261614441871643
tensor([0.2578, 0.6016,